#!/bin/bash -ex

dl() {
    [ "$FAB_HTTP_PROXY" ] && PROXY="--proxy $FAB_HTTP_PROXY"
    cd $2; curl -L -f -O $PROXY $1; cd -
}

SRC="/usr/local/src"

VERSION=4.1.0.4
URL="https://github.com/opencart/opencart/releases/download/$VERSION/opencart-$VERSION.zip"
SHA256=cdef537f5a0a7e1b4ddbe16f589dd2e80b10150a09bfbe93ce76ef2d5c3218c0

dl $URL $SRC
echo "$SHA256  $SRC/opencart-$VERSION.zip" | sha256sum -c -
