#!/bin/bash -ex

DB_NAME=opencart
DB_USER=opencart
DB_PASS=$(mcookie)

SRC=/usr/local/src
WEBROOT=/var/www/opencart
STORAGE=$(dirname $WEBROOT)/opencart-storage

DOMAIN=www.example.com

unzip "$SRC/opencart-"*.zip -d "$SRC/opencart"
mv "$SRC/opencart/upload" "$WEBROOT"
rm -rf "$SRC/opencart"*

cd $WEBROOT
mv $WEBROOT/config-dist.php $WEBROOT/config.php
mv $WEBROOT/admin/config-dist.php $WEBROOT/admin/config.php

a2dissite 000-default
a2ensite opencart
a2enmod rewrite
a2enmod headers

service mariadb start

MYSQL_BATCH="mariadb --user=root --password=$MYSQL_PASS --batch"
$MYSQL_BATCH --execute "
CREATE DATABASE $DB_NAME CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASS';
GRANT ALL PRIVILEGES ON $DB_NAME.* TO '$DB_USER'@'localhost';
FLUSH PRIVILEGES;"

cd $WEBROOT/install
php cli_install.php install --db_hostname localhost --db_username $DB_USER --db_port 3306 --db_database $DB_NAME --db_driver mysqli --db_password $DB_PASS --username admin --password turnkey --email admin@example.com --http_server $DOMAIN/
rm -r $WEBROOT/install
mv $WEBROOT/system/storage $STORAGE
sed -i "s|'DIR_STORAGE', DIR_SYSTEM . 'storage/'|'DIR_STORAGE', '$STORAGE/'|" $WEBROOT/config.php
sed -i "s|'DIR_STORAGE', DIR_SYSTEM . 'storage/'|'DIR_STORAGE', '$STORAGE/'|" $WEBROOT/admin/config.php

service mariadb stop

LOCATIONS="$WEBROOT/image/ $WEBROOT/image/cache/
    $WEBROOT/image/catalog/ $WEBROOT/config.php $WEBROOT/admin/config.php
    $WEBROOT/catalog/ $STORAGE/cache/ $STORAGE/download/ $STORAGE/logs/
    $STORAGE/session/ $STORAGE/upload/
    $STORAGE/vendor/"

for location in $LOCATIONS; do
    chown -R www-data:www-data $location
done

# opencart 4.0 shows a nagging alert
# about moving 'admin' directory from the default location
mv $WEBROOT/admin $WEBROOT/turnkey_admin
sed -i "s|admin|turnkey_admin|g" $WEBROOT/turnkey_admin/config.php
